micro_wake_word:
  models:
    - model: alexa
  on_wake_word_detected:
    then:
      - voice_assistant.start:
          wake_word: !lambda return wake_word;

voice_assistant:
  id: va
  microphone:
    microphone: echo_mic
    channels: 0
    gain_factor: 4
  media_player: echo_media_player
  use_wake_word: false
  noise_suppression_level: 2
  auto_gain: 31dBFS
  volume_multiplier: 2.0
  on_listening:
    - light.turn_on:
        id: atom_led
        blue: 100%
        green: 0%
        red: 0%
        brightness: 100%
  on_tts_start:
    - light.turn_on:
        id: atom_led
        blue: 100%
        green: 0%
        red: 0%
        brightness: 50%
  on_end:
    - light.turn_off: atom_led
    - micro_wake_word.start:
  on_error:
    - light.turn_on:
        id: atom_led
        red: 100%
        green: 0%
        blue: 0%
        brightness: 100%
    - delay: 1s
    - light.turn_off: atom_led
    - micro_wake_word.start:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO39
      inverted: true
    name: "Atom Button"
    on_press:
      - if:
          condition:
            voice_assistant.is_running:
          then:
            - voice_assistant.stop:
          else:
            - micro_wake_word.stop:
            - voice_assistant.start:
