micro_wake_word:
  models:
    - model: alexa
  on_wake_word_detected:
    then:
      - script.execute: stop_wake_word
      - voice_assistant.start:
          wake_word: !lambda return wake_word;

voice_assistant:
  id: va
  microphone:
    microphone: echo_mic
    channels: 0
    gain_factor: 4
  media_player: echo_media_player
  use_wake_word: false
  noise_suppression_level: 2
  auto_gain: 31dBFS
  volume_multiplier: 2.0
  on_client_connected:
    - script.execute: start_wake_word
  on_client_disconnected:
    - script.execute: stop_wake_word
    - light.turn_off: atom_led
  on_listening:
    - light.turn_on:
        id: atom_led
        blue: 100%
        green: 0%
        red: 0%
        brightness: 100%
  on_tts_start:
    - light.turn_on:
        id: atom_led
        blue: 100%
        green: 0%
        red: 0%
        brightness: 50%
  on_end:
    - light.turn_off: atom_led
    - script.execute: start_wake_word
  on_error:
    - light.turn_on:
        id: atom_led
        red: 100%
        green: 0%
        blue: 0%
        brightness: 100%
    - delay: 1s
    - light.turn_off: atom_led
    - script.execute: start_wake_word

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO39
      inverted: true
    name: "Atom Button"
    on_press:
      - if:
          condition:
            voice_assistant.is_running:
          then:
            - voice_assistant.stop:
          else:
            - script.execute: stop_wake_word
            - voice_assistant.start:

script:
  - id: start_wake_word
    then:
      - if:
          condition:
            and:
              - voice_assistant.connected:
              - not:
                  voice_assistant.is_running:
              - not:
                  media_player.is_announcing: echo_media_player
              - not:
                  micro_wake_word.is_running:
          then:
            - micro_wake_word.start:
  - id: stop_wake_word
    then:
      - if:
          condition:
            micro_wake_word.is_running:
          then:
            - micro_wake_word.stop:
